
var GameObjectType = {
    START_STORY: 0,
    START_ARCADE_HARD: 1,
    START_ARCADE_NORMAL: 2,
    LEADERBOARD_ARCADE_HARD: 3,
    LEADERBOARD_ARCADE_NORMAL: 4,
    WONDERMELON: 5,
    ZESTY_MARKET: 6,
    FLOPPY_DISK: 7
};
