
var GameObjectType = {
    MR_NOT: 0,
    START_STORY: 1,
    START_ARCADE_HARD: 2,
    START_ARCADE_NORMAL: 3,
    LEADERBOARD_ARCADE_HARD: 4,
    LEADERBOARD_ARCADE_NORMAL: 5,
    WONDERMELON: 6,
    ZESTY_MARKET: 7,
    FLOPPY_DISK: 8
};
